excluded:
  - DerivedData
  - "**/.build"
  - Pods
  - Generated/

disabled_rules:
  - multiple_closures_with_trailing_closure
  - discarded_notification_center_observer
  - notification_center_detachment
  - orphaned_doc_comment
  - todo
  - switch_case_alignment
  - identifier_name
  - nesting
  - trailing_whitespace

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon 
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

force_cast: warning
force_try: warning
function_body_length:
    warning: 60

legacy_hashing: error

line_length:
  warning: 160
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

private_over_fileprivate:
  validate_extensions: true

vertical_whitespace:
  max_empty_lines: 1
